Lesson 3
Aleksa-esme/Django pull request #3
Opened 2021-04-27 09:49 UTC by Aleksa-esme

2021-04-28 10:22 UTC, Vokler commented
Отвечаю на ваши вопросы:
1. Нужно включить поддержку Django в проекте https://www.jetbrains.com/help/pycharm/django-support7.html#enable-support или проверьте, что вы через PyCharm открыли именно сам проект (как мы это делали на 1ом уроке)
2. Так у вас функция str находится не в классе вообще. Посмотрите внимательнее код с урока и ваш

2021-04-28 19:52 UTC, Aleksa-esme commented
> Отвечаю на ваши вопросы:
> 
> 1. Нужно включить поддержку Django в проекте https://www.jetbrains.com/help/pycharm/django-support7.html#enable-support или проверьте, что вы через PyCharm открыли именно сам проект (как мы это делали на 1ом уроке)
> 2. Так у вас функция str находится не в классе вообще. Посмотрите внимательнее код с урока и ваш

Исправила

2021-04-29 08:33 UTC, Vokler requested changes

2021-04-29 08:33 UTC, Vokler commented on gamesshop/settings.py
> +STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),
Используйте везде один стиль кавычек

2021-04-29 12:59 UTC, Aleksa-esme commented on gamesshop/settings.py
> +STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),
Исправила

2021-04-29 14:09 UTC, merged